# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-06 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message_board_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBoardPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message_board_site.User')),
            ],
        ),
    ]
