# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-07 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_board_site', '0002_messageboardpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_key',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
